// This file is no longer used to store the Firebase configuration directly.
// Instead, the configuration is built from environment variables in `services/firebaseService.js`.
//
// You must set these environment variables in your hosting provider's settings (e.g., Vercel).
//
// Required variables:
//
// VITE_FIREBASE_API_KEY=...
// VITE_FIREBASE_AUTH_DOMAIN=...
// VITE_FIREBASE_PROJECT_ID=...
// VITE_FIREBASE_STORAGE_BUCKET=...
// VITE_FIREBASE_MESSAGING_SENDER_ID=...
// VITE_FIREBASE_APP_ID=...
// VITE_FIREBASE_MEASUREMENT_ID=...
//
// You also need to set the Gemini API Key:
// API_KEY=...
//
// This approach is more secure as it prevents your secret keys from being exposed in your public code.
